Neozaelks/AssoRDJ-Backend

- src/main/java/fr/associationrdj/backend/back/article/Article.java
- src/main/java/fr/associationrdj/backend/back/commentaire/Commentaire.java
- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireController.java
- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireRepository.java
- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireService.java
Création du package "commentaire"
> Commentaire

- src/main/java/fr/associationrdj/backend/back/typedemande/TypeDemande.java
- src/main/java/fr/associationrdj/backend/back/typedemande/TypeDemandeController.java
- src/main/java/fr/associationrdj/backend/back/typedemande/TypeDemandeRepository.java
- src/main/java/fr/associationrdj/backend/back/typedemande/TypeDemandeService.java
creation du package "TypeDemande" (entity, controller, service, repository)
> creation package typedemande

- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireController.java
- src/main/java/fr/associationrdj/backend/back/coordonnee/CoordonneeController.java
- src/main/java/fr/associationrdj/backend/back/demandeContact/DemandeContactController.java
- src/main/java/fr/associationrdj/backend/back/evenement/EvenementController.java
- src/main/java/fr/associationrdj/backend/back/permission/PermissionController.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurController.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurService.java
Modification des @mapping, methode save et rajout des @Requestbody et @Pathvariable
> Modification 

- src/main/java/fr/associationrdj/backend/back/utilisateur/Utilisateur.java
modification de l'import de l'objet permission dans l'entity utilisateur
> Modification Entity Utilisateur

- pom.xml
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurController.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurService.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/dto/UtilisateurDTOFindAll.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/dto/UtilisateurDTOSansMDP.java
Création de :
- UtilisateurDTOFindAll : pour retourner uniquement l'id, le nom et le prénom d'utilisateur sur une méthode findAll().
- UtilisateurDTOSansMDP : pour retourner l'utilisateur sans son mot de passe sur une méthode findById().
> Creation DTO pour Utilisateur

- src/main/java/fr/associationrdj/backend/back/salle/SalleController.java
- src/main/java/fr/associationrdj/backend/back/salle/SalleService.java
- src/main/java/fr/associationrdj/backend/back/salle/dto/SalleDTOFindAll.java
Création d'une DTO sur l'entity Salle pour permettre de récupérer uniquement le nom des salles lors d'une méthode findAll() :
- Rajout d'une classe SalleDTOFindAll dans un package DTO
- modification de la méthode findAll() dans SalleService
- modification du type de retour de la méthode findAll() dans SalleController
> Création de SalleDTOFindAll

- src/main/java/fr/associationrdj/backend/back/reservation/ReservationController.java
- src/main/java/fr/associationrdj/backend/back/reservation/ReservationService.java
- src/main/java/fr/associationrdj/backend/back/reservation/dto/ReservationDTOFindAll.java
Création d'une DTO pour l'Entity Reservation pour la méthode findAll() :
- Création de la classe ReservationDTOFindAll dans un package DTO.
- Modification de la méthode findAll() dans ReservationService.
- Modification du retour de type dans la méthode findAll() de ReservationController.
> Creation ReservationDTOFindAll

- src/main/java/fr/associationrdj/backend/back/article/Article.java
- src/main/java/fr/associationrdj/backend/back/article/ArticleController.java
- src/main/java/fr/associationrdj/backend/back/article/ArticleService.java
- src/main/java/fr/associationrdj/backend/back/article/dto/ArticleDTOFindAll.java
- src/main/java/fr/associationrdj/backend/back/article/dto/ArticleDTOThreeLastArticle.java
> Article DTO

- src/main/java/fr/associationrdj/backend/back/article/ArticleService.java
- src/main/java/fr/associationrdj/backend/back/categorie/CategorieService.java
- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireService.java
- src/main/java/fr/associationrdj/backend/back/coordonnee/CoordonneeService.java
- src/main/java/fr/associationrdj/backend/back/demandeContact/DemandeContactService.java
- src/main/java/fr/associationrdj/backend/back/evenement/EvenementService.java
- src/main/java/fr/associationrdj/backend/back/permission/PermissionService.java
- src/main/java/fr/associationrdj/backend/back/reservation/ReservationService.java
- src/main/java/fr/associationrdj/backend/back/salle/SalleService.java
- src/main/java/fr/associationrdj/backend/back/typedemande/TypeDemandeService.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurService.java
Rajout de commentaires sur les différentes méthodes utilisé dans les services suivant :
- ArticleService
- CategorieService
- CommentaireService
- CoordonneeService
- DeamndeContactService
- EvenementService
- PermissionService
- ReservationService
- SalleService
- TypeDemandeService
- UtilisateurService
> Commentaires

- src/main/java/fr/associationrdj/backend/back/permission/PermissionController.java
- src/main/java/fr/associationrdj/backend/back/permission/PermissionService.java
Modification de :
- PermissionController : modification du chemin de @PutMapping en utilisant un id.
- PermissionService : modification des parametres.
> modification de PermissionController et PermissionService

- src/main/java/fr/associationrdj/backend/back/reservation/Reservation.java
Modification de la jointure entre les entity Reservation et Utilisateur de ManyToMany en OneTO Many
> modification de la jointure Reservation

- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireService.java
- src/main/java/fr/associationrdj/backend/back/reservation/Reservation.java
- src/main/java/fr/associationrdj/backend/back/reservation/dto/ReservationDTOFindAll.java
Modification de :
- Reservation : attribut crenau renommé en creneau
- ReservationDTOFindAll : attribut crenau renommé en creneau
- CommentaireService : correction de la methode updateById()
> modification Reservation, ReservationDTO et CommentaireService

- src/main/java/fr/associationrdj/backend/back/coordonnee/CoordonneeService.java
- src/main/java/fr/associationrdj/backend/back/demandeContact/DemandeContactService.java
- src/main/java/fr/associationrdj/backend/back/evenement/EvenementService.java
Correction des méthodes updatesById() en modifiant les return (exception compris) des services suivant :
- CoordonneesService.
- DemandeContactService.
- EvenementService.
> Correction  Service, ContactService et Evenement

- src/main/java/fr/associationrdj/backend/back/article/dto/ArticleDTOFindAll.java
- src/main/java/fr/associationrdj/backend/back/article/dto/ArticleDTOThreeLastArticle.java
-Modification de articleDTOfindAll -> changement de l'attribut nom en titre
-Modification de articleDTOThreeLastArticle -> changement de l'attribut nom en titre
> Modification des DTO de article

- src/main/java/fr/associationrdj/backend/back/evenement/Evenement.java
Rajout de l'attribut Coordonne et d'une jointure @ManyToOne
> modification de Evenement

- src/main/java/fr/associationrdj/backend/back/evenement/Evenement.java
- src/main/java/fr/associationrdj/backend/back/evenement/dto/EvenementDTOFindAll.java
- src/main/java/fr/associationrdj/backend/back/evenement/dto/EvenementDTONextEvents.java
- src/main/java/fr/associationrdj/backend/back/evenement/dto/EvenementDTONextThreeEvents.java
- src/main/java/fr/associationrdj/backend/back/evenement/dto/EvenementDTONextTwoEvents.java
Modification de l'attribut Coordonnee dans Evenement : Refactorisation en String;
Rajout de l'attribut String lieu dans :
- EvenementDTOFindAll
- EvenementDTONextEvents
- EvenementDTONextThreeEvents
- EvenementDTONextTwoEvents
> Modification de Evenement et de toutes ses DTO

- src/main/java/fr/associationrdj/backend/back/article/ArticleService.java
- src/main/java/fr/associationrdj/backend/back/categorie/CategorieService.java
- src/main/java/fr/associationrdj/backend/back/commentaire/CommentaireService.java
- src/main/java/fr/associationrdj/backend/back/coordonnee/CoordonneeService.java
- src/main/java/fr/associationrdj/backend/back/demandeContact/DemandeContactService.java
- src/main/java/fr/associationrdj/backend/back/evenement/EvenementService.java
- src/main/java/fr/associationrdj/backend/back/permission/PermissionService.java
- src/main/java/fr/associationrdj/backend/back/reservation/ReservationService.java
- src/main/java/fr/associationrdj/backend/back/salle/SalleService.java
- src/main/java/fr/associationrdj/backend/back/typedemande/TypeDemandeService.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurService.java
Modification de toutes les methode updateByID() en rajoutant des conditions == null ?
> Modification de toutes les methodes updateById()

- src/main/java/fr/associationrdj/backend/back/evenement/dto/EvenementDTOFindAll.java
Modification de EvenementDTOFindAll :
- Rajout de l'attribut : categorie, dateFin
> modification event

- src/main/java/fr/associationrdj/backend/back/article/ArticleController.java
- src/main/java/fr/associationrdj/backend/back/article/ArticleService.java
- src/main/java/fr/associationrdj/backend/back/article/dto/ArticleDTOTwoLastArticle.java
-Ajout de la methode pour récupérer les 2 derniers articles
> ajout d'une methode pour récupérer les 2 derniers articles

- src/main/java/fr/associationrdj/backend/back/utilisateur/Utilisateur.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurController.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/UtilisateurService.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/dto/UtilisateurDTOFindAll.java
- src/main/java/fr/associationrdj/backend/back/utilisateur/dto/UtilisateurDTOSansMDP.java
-Ajout du téléchargement d'image pour les utilisateurs 
-Ajout de la récupération d'image pour les utilisateurs 
-Ajout de l'attribut fichier dans le modèle de utilisateur ainsi que dans ses DTO
> Ajout de l'upload
